"""
AgentPrahari Hallucination and Context Faithfulness Guard.
Verifies whether factual statements and numbers generated by LLMs are grounded in the provided reference context.
"""

from __future__ import annotations
import re
from typing import List, Set, Tuple
from agentprahari.core.config import PrahariConfig
from agentprahari.core.result import GuardCategory, Severity, Violation
from agentprahari.output_guards.base import BaseOutputGuard


class HallucinationGuard(BaseOutputGuard):
    """
    Checks if model output makes ungrounded claims or fabricates numbers/entities
    not present in the provided source context.
    """

    @property
    def name(self) -> str:
        return "HallucinationGuard"

    def _extract_numbers_and_metrics(self, text: str) -> Set[str]:
        """Extracts percentages, currency, and numerical values."""
        found = set()
        # Percentages like 45% or 99.9%
        for p in re.findall(r"\b\d+(?:\.\d+)?%", text):
            found.add(p)
        # Currency like $500, €100
        for c in re.findall(r"[$€£]\s*\d+(?:,\d{3})*(?:\.\d+)?", text):
            found.add(c.replace(" ", ""))
        # Years / Dates like 2024, 1999
        for y in re.findall(r"\b(?:19|20)\d{2}\b", text):
            found.add(y)
        return found

    def evaluate(
        self,
        output_text: str,
        config: PrahariConfig
    ) -> Tuple[str, List[Violation]]:
        if not config.check_hallucination or not config.grounding_context:
            return output_text, []

        violations: List[Violation] = []
        context_str = config.grounding_context.lower()

        # Check for fabricated metrics or numbers that do not appear anywhere in context
        output_metrics = self._extract_numbers_and_metrics(output_text)
        context_metrics = self._extract_numbers_and_metrics(config.grounding_context)

        fabricated_metrics = output_metrics - context_metrics
        if fabricated_metrics:
            violations.append(Violation(
                rule_id="OUT_UNGROUNDED_METRICS",
                message=f"Model output cited numerical figures/metrics not found in grounding context: {list(fabricated_metrics)}",
                severity=Severity.MEDIUM,
                category=GuardCategory.OUTPUT,
                guard_name=self.name,
                matched_content=", ".join(fabricated_metrics),
                details={"unsupported_numbers": list(fabricated_metrics)}
            ))

        return output_text, violations
